name: CI SAST Scan

on: [push]

jobs: 
  sast_scan: 
    name: Execute Bandit Scan
    runs-on: unbuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r .
